### PR TITLE
feat: overhaul status chart design

### PR DESCRIPTION
**Pull request by crnvl**
I think these changes would make the status page chart a bit prettier.

Changes:
- set `pointStyle` to `false`
- change label date format to `hh:mm a` (I think the mention of the day is unnecessary and introduces clutter)
- set line `tension` to `0.15` for a smoother line
- set `fill` to `false`

Screenshot of reworked chart:
image

### CODE REVIEW

**Comment by ConnysCode** [comment]
I don't like the new styling. There is no consistency between it and the rest of the website. It also rises accessibility concerns.

However, i do like the new date formatting.

**Review by ConnysCode — CHANGES_REQUESTED** [review]
I don't like the new styling. There is no consistency between it and the rest of the website. It also rises accessibility concerns.

However, i do like the new date formatting.

**Comment by crnvl** [comment]
related to [3cdb4be](https://github.com/xp-bot/dashboard/pull/57/commits/3cdb4be23f756a943ddf873985100b2fb255895d)

Adjusted fill style and border width to previous values. If you were referring to the removal of points with accessibility concerns, I feel like not having them renders a clearer and easier to view graph than leaving them in (View second attachment). I also think that a subtle smoothness of the curves benefits the design a lot. 

Changes:
image

Example for similar chart on [discordstatus.com](https://discordstatus.com)
image

**Comment by ConnysCode** [comment]
> related to [3cdb4be](https://github.com/xp-bot/dashboard/pull/57/commits/3cdb4be23f756a943ddf873985100b2fb255895d)
> 
> Adjusted fill style and border width to previous values. If you were referring to the removal of points with accessibility concerns, I feel like not having them renders a clearer and easier to view graph than leaving them in (View second attachment). I also think that a subtle smoothness of the curves benefits the design a lot.
> 
> Changes: image
> 
> Example for similar chart on [discordstatus.com](https://discordstatus.com) image

In my opinion, the unconstrained behaviour of the lines, does not match our relatively calculated and streamlined approach on design. Adding the points back, provides some clarity on the expected positioning of data points.

You cannot really compare one component to another one on another website with a whole different design philosophy.

**Comment by crnvl** [comment]
The reference image was meant to visualise, how another (quite big) service also does not use points while having a very accessible chart. 
image
On lower resolution screens, points are very close to another and introduce noise to the field of view. Furthermore, smoothing the line helps with overflowing edges as shown in the image above.

**Comment by ConnysCode** [comment]
> The reference image was meant to visualise, how another (quite big) service also does not use points while having a very accessible chart. image On lower resolution screens, points are very close to another and introduce noise to the field of view. Furthermore, smoothing the line helps with overflowing edges as shown in the image above.

Yes, i do and did agree with smoothing the lines.

**Comment by crnvl** [comment]
Alright, what about the points? I think it'd be nice to remove them. If you still need exact info on a specific record, you can still hover over the chart to reveal exact info

**Comment by ConnysCode** [comment]
> Alright, what about the points? I think it'd be nice to remove them. If you still need exact info on a specific record, you can still hover over the chart to reveal exact info

The points need to stay, we can talk about making them smaller, but in the current design - they are necessary.

**Pull request closed without merging**
